# Generated by Django 3.2.9 on 2021-11-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KAMULogin', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='posts',
        ),
    ]
