# Generated by Django 3.2.9 on 2021-11-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KAMULogin', '0009_auto_20211116_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
