# Generated by Django 3.2.9 on 2021-11-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KAMULogin', '0010_alter_blogposts_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
