# Generated by Django 3.2.9 on 2021-11-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KAMULogin', '0011_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
